### ISSUE TITLE
Emitted light from deleted token remains until refresh.

### ISSUE THREAD

**Issue by RogueEntityX** [theripper93/Levels#46]
If a token that emits light is placed on the canvas, or a token already on the canvas is changed to emit light, that light remains when the token is deleted until a refresh is done (F5, or view another scene and then go back).

I tried this in a world with only libWrapper, Wall Height, Better Roofs, and Levels enabled. If Levels is then disabled, the issue no longer persists.

Steps to reproduce:
1) Create a scene. Token Vision, Fog of Exploration, and Unrestricted Vision Range don't seem to matter, but make sure the darkness level is set high enough to distinguish when light is being emitted.
2) Create an actor, and set the Dim or Bright light emission of the prototype token (I used various combinations of dim/bright, at varying radii).
3) Drag the actor onto the canvas. Note area illuminated by the token.
![image](https://user-images.githubusercontent.com/72455534/130688972-a7ed43bf-7c37-4562-a2d0-7bc2cdb65b41.png)

4) Delete the actor from the canvas. Note the area is still illuminated, even though the token is gone.
![image](https://user-images.githubusercontent.com/72455534/130689013-6c2c1d16-a08b-4df5-b427-b609d51aeb56.png)

5) Refresh to clear the emitted light.
6) Disable Levels and repeat and the issue does not occur.

No error messages in console. This happens whether from the app, firefox, or chrome.

**Comment by theripper93** [comment]
should be fixed

**Comment by RogueEntityX** [comment]
Just tried with the newly released 1.7.6, and it's still happening.

**Comment by theripper93** [comment]
that is strange, it seems to be working fine on my end now, same steps as before?

**Comment by RogueEntityX** [comment]
https://user-images.githubusercontent.com/72455534/130699766-57ba5fc7-aca8-4546-bf17-1eb373169ab7.mp4

**Comment by theripper93** [comment]
i identified the problem, it was due to a bug in foundry, i implemented a workaround and it should work fine now. Let me know

**Comment by RogueEntityX** [comment]
Yup, that seems to have fixed it. Thanks!
